spring:
  application:
    name: business-reg
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.229.150:8848



dubbo:
  scan:
    base-packages: com.kimi.myshop.plus.business.controller
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://192.168.229.150:8848
    port: 80

server:
  # ${random.int[9000,9999]} 随机端口
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: "*"
