spring:
  application:
    name: business-oauth2
  #  main:
  #    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.229.150:8848
    sentinel:
      transport:
        dashboard: localhost:8765
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://192.168.229.150:3306/shop_plus_oauth2?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false
    username: root
    password: root
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:

    host: 192.168.229.150
    port: 6379

    # 集群配置，上生产使用
#    cluster:
#      nodes:
    lettuce:
      pool:
        # 连接池中的最小空闲连接，默认0
        min-idle: 0
        # 链接池中的最大空闲连接，默认8
        max-idle: 8
        # 连接池最大连接数，（使用负数表示没有限制），默认8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负数表示没有限制），默认 -1ms
        max-wait: -1ms

dubbo:
  scan:
    base-packages: com.funtl.myshop.plus.business.controller, com.kimi.myshop.plus.business.service
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://192.168.229.150:8848
    port: 80


feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  sentinel:
    enabled: true

server:
  # ${random.int[9000,9999]} 随机端口
  port: 9001

management:
  endpoints:
    web:
      exposure:
        include: "*"

business:
  oauth2:
    grant_type: password
    client_id: client
    client_secret: secret
